Repository CMPUT301F21T09/BudgetProjectName, pull requests merged in 2021-11, with the labels that each got.

#84 Create habit details view
  src/app/src/main/AndroidManifest.xml
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ExampleActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventModel.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
  src/app/src/main/res/drawable/ic_comment_negative.xml
  src/app/src/main/res/drawable/ic_comment_positive.xml
  src/app/src/main/res/drawable/ic_friday_negative.xml
  src/app/src/main/res/drawable/ic_friday_positive.xml
  src/app/src/main/res/drawable/ic_image_negative.xml
  src/app/src/main/res/drawable/ic_image_positive.xml
  src/app/src/main/res/drawable/ic_map_marker_negative.xml
  src/app/src/main/res/drawable/ic_map_marker_positive.xml
  src/app/src/main/res/drawable/ic_monday_negative.xml
  src/app/src/main/res/drawable/ic_monday_positive.xml
  src/app/src/main/res/drawable/ic_saturday_negative.xml
  src/app/src/main/res/drawable/ic_saturday_positive.xml
  src/app/src/main/res/drawable/ic_sunday_negative.xml
  src/app/src/main/res/drawable/ic_sunday_positive.xml
  src/app/src/main/res/drawable/ic_thursday_negative.xml
  src/app/src/main/res/drawable/ic_thursday_positive.xml
  src/app/src/main/res/drawable/ic_trash_can.xml
  src/app/src/main/res/drawable/ic_tuesday_negative.xml
  src/app/src/main/res/drawable/ic_tuesday_positive.xml
  src/app/src/main/res/drawable/ic_wednesday_negative.xml
  src/app/src/main/res/drawable/ic_wednesday_positive.xml
  src/app/src/main/res/layout/activity_example.xml
  src/app/src/main/res/layout/activity_view_habit_event_custom_list.xml
  src/app/src/main/res/layout/activity_view_habit_screen.xml
  src/app/src/main/res/menu/menu_view_habit_details_screen.xml
  src/app/src/main/res/values/strings.xml
Labels: user requirement

#104 Fix ViewHabitActivity
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
Labels: bug

#123 User signup
  src/app/build.gradle
  src/app/src/main/AndroidManifest.xml
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/AuthorizationService.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserRegisterActivity.java
  src/app/src/main/res/layout/activity_user_login.xml
  src/app/src/main/res/layout/activity_user_register.xml
Labels: user requirement

#125 Fix bug - the HabitEventModel has changed
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
Labels: bug

#128 User sign in
  src/app/src/main/AndroidManifest.xml
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserLoginActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserRegisterActivity.java
  src/app/src/main/res/layout/activity_user_login.xml
  src/app/src/main/res/layout/activity_user_register.xml
Labels: user requirement

#135 Authorization service and user logout
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/AuthorizationService.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileFragment.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserLoginActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserRegisterActivity.java
Labels: user requirement

#143 View habit details with controllers and firestore
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ExampleActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventModel.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
Labels: user requirement

#156 Fix deleteHabitEvent
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
Labels: bug

#161 Habit List
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileFragment.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitFragment.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitListController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserHabitCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitActivity.java
Labels: user requirement

#165 make pressing a habit more intuitive
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserHabitCustomList.java
Labels: enhancement

#167 make habit title in center
  src/app/src/main/res/layout/activity_view_habit_screen.xml
Labels: bug

#188 bug fix for viewhabitevent
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
Labels: bug

#187 Remove deprecated habit model
  src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/ExampleInstrumentedTest.java
  src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/HabitEventTest.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/CurrentUserProfileFragment.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DailyHabitFragment.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitListController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitModel.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/UserHabitCustomList.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
  src/app/src/test/java/com/cmput301f21t09/budgetprojectname/ExampleUnitTest.java
Labels: refactor

#202 Habitevent idconnection bug
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/HabitEventController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/ViewHabitEventActivity.java
Labels: bug

#246 habit privacy functionality
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/controllers/HabitController.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/HabitModel.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/models/IHabitModel.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
  src/app/src/main/res/layout/activity_define_habit.xml
  src/app/src/main/res/values/strings.xml
  src/app/src/main/res/values/themes.xml
Labels: user requirement

#248 update mockups
  doc/uimock/StoryBoard.png
  doc/uimock/frames/EditHabitScreen.png
  doc/uimock/frames/NewHabitScreen.png
Labels: documentation

#252 ui improvements
  src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitActivityTest.java
  src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/DefineHabitEventActivityTest.java
  src/app/src/androidTest/java/com/cmput301f21t09/budgetprojectname/HabitEventTest.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
  src/app/src/main/res/layout/activity_define_habit.xml
  src/app/src/main/res/layout/activity_define_habit_event.xml
  src/app/src/main/res/layout/activity_view_habit_screen.xml
  src/app/src/main/res/layout/fragment_daily_habit.xml
  src/app/src/main/res/menu/menu_define_habit.xml
Labels: enhancement

#260 Fix Request to follow ->Update social map bug
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/AnotherUserProfileActivity.java
Labels: bug

#261 fix null locality bug
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
Labels: bug

#278 Make add/edit habit event screen scrollable
  src/app/src/main/res/layout/activity_define_habit_event.xml
Labels: enhancement

#279 Fix a bug in View Habit Details and View Habit Event Screen
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
Labels: bug

#281 Location Bug fix & Image bug fix
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/DefineHabitEventActivity.java
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
  src/app/src/main/res/layout/activity_view_habit_event.xml
Labels: bug

#289 Add an onResume() to ViewHabitEventActivity
  src/app/src/main/java/com/cmput301f21t09/budgetprojectname/views/activities/ViewHabitEventActivity.java
Labels: bug
